[features]
seeds = false
skip-lint = false
[programs.localnet]
mycalculatordapp = "51SM3759uCrzG1PJn7vawysoMktzhuqGbmG5gMTu7Wru"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/devgenesis/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
